title       = "osrm"
baseURL     = "https://osrm-cli.tamnd.com/"
description = "A command line for osrm."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/osrm-cli"
